cloudnative-backend:
  service:
    type: LoadBalancer
  replicaCount: 1
  containerPort: 80
  image:
    repository: ghcr.io/parrotwings/ipapuga-ui
    pullPolicy: IfNotPresent
    tag: main-e8da1b60
  imagePullSecrets:
    - name: regcred
  nameOverride: "ipapuga-fe"
  fullnameOverride: "ipapuga-fe"
  healthCheckPath: /health
  resources:
    limits:
      memory: "80Mi"
  configMap:
    nginx.conf: >-
      server {
          listen 80;
          server_name localhost;

          location /health {
              access_log off;
              add_header "Content-Type" "application/json";
              return 200 "{\"status\": \"OK\"}";
          }

          location / {
              alias /usr/share/nginx/html/;

              try_files $uri $uri/ /index.html;

              location ~* assets/.*\.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                  expires 1y;
                  gzip on;
                  access_log off;
                  add_header Cache-Control "public";
              }
          }

          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;
      }
      

  volumes:
    - name: ipapuga-fe-cm
      configMap:
        name: ipapuga-fe

  volumeMounts:
    - name: ipapuga-fe-cm
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
  ingress:
    enabled: false
    className: "traefik"
    hosts:
      - host: "ipapuga.k8s.kperczynski.click"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ipapuga.k8s.kperczynski.click
